Repository rka0917/elasticsearch, pull requests merged in 2018-02, with the labels that each got.

#9 Doc: improve documentation of RestRequest #8
  server/src/main/java/org/elasticsearch/rest/RestRequest.java
Labels: documentation

#24 Doc: Improve documention of public method of RestController #23
  server/src/main/java/org/elasticsearch/rest/RestController.java
Labels: documentation

#26 Doc: add contracts to the test method of PathTrieTest #25
  server/src/test/java/org/elasticsearch/common/path/PathTrieTests.java
Labels: documentation

#32 refactor: Merged the builder and TrieNode with PathTrie.
  server/src/main/java/org/elasticsearch/common/path/PathTrie.java
  server/src/main/java/org/elasticsearch/common/path/PathTrieBuilder.java
  server/src/main/java/org/elasticsearch/common/path/TrieNode.java
  server/src/main/java/org/elasticsearch/rest/RestController.java
  server/src/main/java/org/elasticsearch/rest/RestUtils.java
  server/src/test/java/org/elasticsearch/common/path/PathTrieTests.java
Labels: refactor

#34 fix: The class name for FSTRepresentationTests is wrong.
  server/src/test/java/org/elasticsearch/common/path/FSTRepresentationTests.java
Labels: enhancement

#36 fix: Extra example. before OuterClass that shouldn't be there.
  server/src/main/java/org/elasticsearch/common/path/Test.java
Labels: enhancement

#31 Doc: add contracts to the tests of the class RestUtilsTests #30
  server/src/test/java/org/elasticsearch/rest/RestUtilsTests.java
Labels: documentation

#29 Doc: add contracts to the RestRequestTests class #28
  server/src/test/java/org/elasticsearch/rest/RestRequestTests.java
Labels: documentation
